### ISSUE TITLE
Tipr doesn't work with elements that are descendants of elements with position:absolute

### ISSUE THREAD

**Issue by r3wt** [Tipue/Tipr#2]
I'm not entirely sure why, but here's the relative code to the problem:

*HTML*
```html
<li>
	<span class="chat-name">Hans Joseph&nbsp;&nbsp;<span class="convo-notification">0</span></span>
	<span class="time">24.05.2014</span>
	<!-- BUTTONS ON THE RIGHT, SHOWN ON HOVER, With tooltips -->
	<div class="actions">
		<div class="view" data-tip="View"></div>
		<div class="delete" data-tip="Delete"></div>
	</div>
</li>
```
*CSS*
```css
.gm-chat.list > ul > li > .actions {
	display:none;
	position: absolute;
	top: 8px;
	right: 8px;
}
.gm-chat.list > ul > li > .actions > .view {
	background:url('messages.png'); background-repeat:no-repeat; 
	width:23px; height:23px; background-size:100% 100%; float:left; margin-right: 4px; cursor:pointer;
}
.gm-chat.list > ul > li > .actions > .delete {
	background:url('delete.png'); background-repeat:no-repeat; width:23px;
	height:23px; background-size:100% 100%; float:left; cursor:pointer;
}
.gm-chat.list > ul > li:hover > .actions{
	display: inline-block;
}
```
